// Generated by Supabase CLI: supabase gen types typescript --project-id [ID] > src/types/database.types.ts
// Replace this file after avoir lancé la commande ci-dessus

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      clients: {
        Row: {
          id: string
          email: string
          full_name: string | null
          company_name: string | null
          created_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          company_name?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string | null
          company_name?: string | null
          created_at?: string
        }
      }
      projects: {
        Row: {
          id: string
          client_id: string
          name: string
          status: 'active' | 'paused' | 'delivered'
          started_at: string | null
          estimated_at: string | null
          progress_pct: number
          total_amount_ht: number | null
          deposit_paid_at: string | null
          balance_paid_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          client_id: string
          name: string
          status?: 'active' | 'paused' | 'delivered'
          started_at?: string | null
          estimated_at?: string | null
          progress_pct?: number
          total_amount_ht?: number | null
          deposit_paid_at?: string | null
          balance_paid_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          client_id?: string
          name?: string
          status?: 'active' | 'paused' | 'delivered'
          started_at?: string | null
          estimated_at?: string | null
          progress_pct?: number
          total_amount_ht?: number | null
          deposit_paid_at?: string | null
          balance_paid_at?: string | null
          created_at?: string
        }
      }
      project_steps: {
        Row: {
          id: string
          project_id: string
          title: string
          description: string | null
          status: 'pending' | 'active' | 'done'
          completed_at: string | null
          sort_order: number
        }
        Insert: {
          id?: string
          project_id: string
          title: string
          description?: string | null
          status?: 'pending' | 'active' | 'done'
          completed_at?: string | null
          sort_order?: number
        }
        Update: {
          id?: string
          project_id?: string
          title?: string
          description?: string | null
          status?: 'pending' | 'active' | 'done'
          completed_at?: string | null
          sort_order?: number
        }
      }
      documents: {
        Row: {
          id: string
          project_id: string
          type: 'devis' | 'contrat' | 'facture_acompte' | 'facture_solde' | 'autre'
          label: string
          storage_path: string | null
          amount_ht: number | null
          signed_at: string | null
          signature_data: string | null
          paid_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          project_id: string
          type: 'devis' | 'contrat' | 'facture_acompte' | 'facture_solde' | 'autre'
          label: string
          storage_path?: string | null
          amount_ht?: number | null
          signed_at?: string | null
          signature_data?: string | null
          paid_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          project_id?: string
          type?: 'devis' | 'contrat' | 'facture_acompte' | 'facture_solde' | 'autre'
          label?: string
          storage_path?: string | null
          amount_ht?: number | null
          signed_at?: string | null
          signature_data?: string | null
          paid_at?: string | null
          created_at?: string
        }
      }
      vault_credentials: {
        Row: {
          id: string
          project_id: string
          label: string
          service: string | null
          type: 'api' | 'dns' | 'hosting' | 'cms' | 'autre'
          encrypted_value: string
          created_at: string
        }
        Insert: {
          id?: string
          project_id: string
          label: string
          service?: string | null
          type: 'api' | 'dns' | 'hosting' | 'cms' | 'autre'
          encrypted_value: string
          created_at?: string
        }
        Update: {
          id?: string
          project_id?: string
          label?: string
          service?: string | null
          type?: 'api' | 'dns' | 'hosting' | 'cms' | 'autre'
          encrypted_value?: string
          created_at?: string
        }
      }
      project_briefs: {
        Row: {
          id: string
          project_id: string
          project_type: 'crm' | 'site' | 'auto' | 'autre' | null
          activity: string | null
          team: string | null
          current_process: string | null
          blockers: string | null
          ideal_tool: string | null
          tech_constraints: string | null
          v1_priorities: string | null
          context: string | null
          meta: Json | null
          conversation_history: Json | null
          submitted_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          project_id: string
          project_type?: 'crm' | 'site' | 'auto' | 'autre' | null
          activity?: string | null
          team?: string | null
          current_process?: string | null
          blockers?: string | null
          ideal_tool?: string | null
          tech_constraints?: string | null
          v1_priorities?: string | null
          context?: string | null
          meta?: Json | null
          conversation_history?: Json | null
          submitted_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          project_id?: string
          project_type?: 'crm' | 'site' | 'auto' | 'autre' | null
          activity?: string | null
          team?: string | null
          current_process?: string | null
          blockers?: string | null
          ideal_tool?: string | null
          tech_constraints?: string | null
          v1_priorities?: string | null
          context?: string | null
          meta?: Json | null
          conversation_history?: Json | null
          submitted_at?: string | null
          created_at?: string
        }
      }
      sav_tickets: {
        Row: {
          id: string
          project_id: string
          title: string
          body: string | null
          status: 'open' | 'in_progress' | 'closed'
          source_app: string | null
          assigned_to: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          project_id: string
          title: string
          body?: string | null
          status?: 'open' | 'in_progress' | 'closed'
          source_app?: string | null
          assigned_to?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          project_id?: string
          title?: string
          body?: string | null
          status?: 'open' | 'in_progress' | 'closed'
          source_app?: string | null
          assigned_to?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      token_ledger: {
        Row: {
          id: string
          project_id: string
          delta: number
          label: string
          created_at: string
        }
        Insert: {
          id?: string
          project_id: string
          delta: number
          label: string
          created_at?: string
        }
        Update: {
          id?: string
          project_id?: string
          delta?: number
          label?: string
          created_at?: string
        }
      }
      admins: {
        Row: {
          id: string
          email: string
          created_at: string
        }
        Insert: {
          id: string
          email: string
          created_at?: string
        }
        Update: {
          id?: string
          email?: string
          created_at?: string
        }
      }
    }
  }
}
